_common: !include "../default.yaml"
name:                salak-toml
synopsis:            Configuration Loader for toml
description:         Toml support for [salak](https://hackage.haskell.org/package/salak).
<<: *legal
extra-source-files:
- README.md
- salak.toml
- CHANGELOG.md

dependencies:
  - base                 >= 4.10   && < 5
  - salak                >= 0.3.5  && < 0.4
  - text                 >= 1.2.3  && < 1.3
  - time                 >= 1.8.0  && < 1.10
  - tomland              >= 1.1.0  && < 1.2
  - unordered-containers >= 0.2.10 && < 0.3
  # - htoml

library:
  source-dirs: src
  exposed-modules:
    - Salak.Toml
    # - Salak.HToml

benchmarks:
  salak-toml-bench:
    main: SalakTomlBench.hs
    source-dirs:
      - bench
      - src
    ghc-options: -rtsopts -threaded -with-rtsopts=-K1K
    other-modules:
      - Salak.Toml
    dependencies:
      - criterion

tests:
  salak-toml-test:
    main: SalakTomlSpec.hs
    source-dirs:
      - test
      - src
    ghc-options: -rtsopts -threaded -with-rtsopts=-K1K
    dependencies:
      - hspec == 2.*
      - QuickCheck < 2.14
      - random
      - text
      - mtl
      - exceptions
