_common: !include "../default.yaml"
name:                salak-toml
synopsis:            Configuration Loader for toml
<<: *legal
extra-source-files:
- README.md
- salak.toml

dependencies:
  - base >= 4.10 && < 5
  - salak
  - tomland >= 1.0 && < 1.2
  - unordered-containers
  - time
  - text
  # - htoml

library:
  source-dirs: src
  exposed-modules:
    - Salak.Toml
    # - Salak.HToml

benchmarks:
  salak-toml-bench:
    main: SalakTomlBench.hs
    source-dirs:
      - bench
      - src
    ghc-options: -rtsopts -threaded -with-rtsopts=-K1K
    other-modules:
      - Salak.Toml
    dependencies:
      - criterion

tests:
  salak-toml-test:
    main: SalakTomlSpec.hs
    source-dirs:
      - test
      - src
    ghc-options: -rtsopts -threaded -with-rtsopts=-K1K
    dependencies:
      - hspec == 2.*
      - QuickCheck < 2.14
      - text
      - mtl
      - exceptions
