- &legal
  version:             0.3.2
  homepage:            https://github.com/leptonyu/salak#readme
  license:             BSD3
  author:              Daniel YU
  maintainer:          Daniel YU <leptonyu@gmail.com>
  copyright:           (c) 2018 Daniel YU
  category:            Library, Configuration
  ghc-options: -Wall -fno-warn-orphans -fno-warn-missing-signatures
