- &legal
  version:             0.3.3.2
  homepage:            https://github.com/leptonyu/salak#readme
  license:             MIT
  author:              Daniel YU
  maintainer:          Daniel YU <leptonyu@gmail.com>
  copyright:           2019 Daniel YU
  category:            Library, Configuration
  ghc-options: -Wall -fno-warn-orphans -fno-warn-missing-signatures
  default-extensions:
    - RecordWildCards
    - TupleSections
    - OverloadedStrings
    - ScopedTypeVariables
    - FlexibleInstances
    - MultiParamTypeClasses
    - DeriveGeneric