name:                salak
version:             0.1.6
synopsis:            Configuration Loader
description:         Configuration Loader for Production in Haskell
homepage:            https://github.com/leptonyu/salak#readme
license:             BSD3
author:              Daniel YU
maintainer:          Daniel YU <leptonyu@gmail.com>
copyright:           (c) 2018 Daniel YU
category:            Library
extra-source-files:
- README.md
- test/salak.yml
ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints -fno-warn-orphans -fno-warn-missing-signatures

dependencies:
  - base >= 4.11 && < 5
  - unordered-containers
  - aeson
  - yaml
  - text
  - scientific
  - vector
  - directory
  - filepath

library:
  source-dirs: src
  exposed-modules:
    - Data.Salak
  other-modules:
    - Data.Salak.Types
    - Data.Salak.Environment 
    - Data.Salak.CommandLine
    - Data.Salak.Aeson
    - Data.Salak.Yaml
    - Data.Salak.Operation

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck
      - aeson-pretty
      - bytestring
