name:                salak
version:             0.2.5
synopsis:            Configuration Loader
homepage:            https://github.com/leptonyu/salak#readme
license:             BSD3
author:              Daniel YU
maintainer:          Daniel YU <leptonyu@gmail.com>
copyright:           (c) 2018 Daniel YU
category:            Library
extra-source-files:
- README.md
- test/salak.yml
ghc-options: -Wall -fno-warn-orphans -fno-warn-missing-signatures

dependencies:
  - base >= 4.7 && < 5
  - unordered-containers
  - vector
  - aeson 
  - yaml
  - text
  - scientific
  - mtl
  - transformers
  - pqueue
  - containers
  - attoparsec
  - unordered-containers
  - data-default
  - filepath
  - directory

library:
  source-dirs: src
  exposed-modules:
    - Salak
  other-modules:
    - Salak.Types
    - Salak.Env
    - Salak.Json
    - Salak.Prop
    - Salak.Dynamic

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck
