_common: !include "../default.yaml"
name:                salak-yaml
synopsis:            Configuration Loader for yaml
<<: *legal
extra-source-files:
- README.md
- salak.yml

dependencies:
  - base >= 4.10 && < 5
  - salak
  - libyaml
  - conduit
  - text

library:
  source-dirs: src
  exposed-modules:
    - Salak.Yaml

benchmarks:
  salak-yaml-bench:
    main: SalakYamlBench.hs
    source-dirs:
      - bench
      - src
    ghc-options: -rtsopts -threaded -with-rtsopts=-K1K
    dependencies:
      - criterion

tests:
  salak-yaml-test:
    main: SalakYamlSpec.hs
    source-dirs:
      - test
      - src
    ghc-options: -rtsopts -threaded -with-rtsopts=-K1K
    dependencies:
      - hspec == 2.*
      - QuickCheck < 2.14
      - text
      - mtl
      - exceptions
