_common: !include "../default.yaml"
name:                salak-yaml
synopsis:            Configuration Loader for yaml
<<: *legal
extra-source-files:
- README.md
- salak.yml

dependencies:
  - base    >= 4.10  && < 5
  - conduit >= 1.3.1 && < 1.4
  - libyaml >= 0.1.1 && < 0.2
  - salak   >= 0.3.5 && < 0.4
  - text    >= 1.2.3 && < 1.3

library:
  source-dirs: src
  exposed-modules:
    - Salak.Yaml

benchmarks:
  salak-yaml-bench:
    main: SalakYamlBench.hs
    source-dirs:
      - bench
      - src
    ghc-options: -rtsopts -threaded -with-rtsopts=-K1K
    dependencies:
      - criterion

tests:
  salak-yaml-test:
    main: SalakYamlSpec.hs
    source-dirs:
      - test
      - src
    ghc-options: -rtsopts -threaded -with-rtsopts=-K1K
    dependencies:
      - hspec == 2.*
      - QuickCheck < 2.14
      - text
      - mtl
      - exceptions
