_common: !include "../default.yaml"
name:                salak-yaml
version:             0.2.8
synopsis:            Configuration Loader for yaml
<<: *legal
extra-source-files:
- README.md
- test/salak.yml

dependencies:
  - base >= 4.10 && < 5
  - salak == 0.2.8
  - aeson 
  - yaml
  - mtl
  - unordered-containers
  - vector

library:
  source-dirs: src
  exposed-modules:
    - Salak.Load.Yaml

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck < 2.14
      - text
