_common: !include "../default.yaml"
name:                salak
synopsis:            Configuration (re)Loader and Parser.
<<: *legal
extra-source-files:
- README.md

dependencies:
  - base                 >= 4.10    && < 5
  - bytestring           >= 0.10.8  && < 0.11
  - containers           >= 0.6.0   && < 0.7
  - data-default         >= 0.7.1   && < 0.8
  - dlist                >= 0.8.0   && < 0.9
  - directory            >= 1.3.3   && < 1.4
  - filepath             >= 1.4.2   && < 1.5
  - time                 >= 1.8.0   && < 1.10
  - exceptions           >= 0.10.2  && < 0.11
  - mtl                  >= 2.2.2   && < 2.3
  - hashable             >= 1.2.7.0 && < 1.4
  - text                 >= 1.2.3   && < 1.3
  - heaps                >= 0.3.6   && < 0.4
  - megaparsec           >= 7.0.5   && < 7.1
  - scientific           >= 0.3.6   && < 0.4
  - menshen              >= 0.0.3   && < 0.1
  - unliftio-core        >= 0.1.2   && < 0.2
  - unordered-containers >= 0.2.10  && < 0.3

library:
  source-dirs: src
  exposed-modules:
    - Salak
    - Salak.Trie
    - Salak.Internal
  other-modules:
    - Salak.Internal.Key
    - Salak.Internal.Val
    - Salak.Internal.Source
    - Salak.Internal.Prop
    - Salak.Internal.Writable

benchmarks:
  salak-bench:
    main: SalakBench.hs
    source-dirs:
      - bench
    ghc-options: -rtsopts -threaded -with-rtsopts=-K1K
    dependencies:
      - criterion
      - salak

tests:
  salak-test:
    main: Spec.hs
    source-dirs:
      - test
      - src
    ghc-options: -rtsopts -threaded -with-rtsopts=-K1K
    dependencies:
      - hspec == 2.*
      - QuickCheck < 2.14
      - random
    verbatim:
      build-tool-depends:
        hspec-discover:hspec-discover