_common: !include "../default.yaml"
name:                salak
synopsis:            Configuration (re)Loader and Parser.
<<: *legal
extra-source-files:
- README.md

dependencies:
  - base >= 4.10 && < 5
  - text
  - bytestring
  - scientific
  - time
  - mtl
  - megaparsec
  - data-default
  - filepath
  - directory
  - menshen
  - unliftio-core
  - heaps
  - hashable
  - unordered-containers
  - containers
  - exceptions
  - dlist

library:
  source-dirs: src
  exposed-modules:
    - Salak
    - Salak.Trie
    - Salak.Internal
  other-modules:
    - Salak.Internal.Key
    - Salak.Internal.Val
    - Salak.Internal.Source
    - Salak.Internal.Prop
    - Salak.Internal.Writable


benchmarks:
  bench:
    main: SalakBench.hs
    source-dirs:
      - src
      - bench
    dependencies:
      - criterion

tests:
  spec:
    main: SalakSpec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck < 2.14
      - random
    verbatim:
      build-tool-depends:
        hspec-discover:hspec-discover