_common: !include "../default.yaml"
name:                salak
synopsis:            Configuration (re)Loader and Parser.
<<: *legal
extra-source-files:
- README.md

dependencies:
  - base >= 4.10 && < 5
  - text
  - bytestring
  - scientific
  - time
  - mtl
  - attoparsec
  - data-default
  - filepath
  - directory
  - menshen
  - unliftio-core
  - heaps
  - hashable
  - unordered-containers
  - exceptions

library:
  source-dirs: src
  exposed-modules:
    - Salak
    - Salak.Trie
    - Salak.Internal
  other-modules:
    - Salak.Internal.Key
    - Salak.Internal.Val
    - Salak.Internal.Source
    - Salak.Internal.Prop

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck < 2.14
      - random
