_common: !include "../default.yaml"
name:                salak
version:             0.2.7
synopsis:            Configuration Loader
<<: *legal
extra-source-files:
- README.md

dependencies:
  - base >= 4.10 && < 5
  - text
  - scientific
  - time
  - mtl
  - pqueue
  - containers
  - attoparsec
  - data-default
  - filepath
  - directory
  - menshen

library:
  source-dirs: src
  exposed-modules:
    - Salak
    - Salak.Load
  other-modules:
    - Salak.Types
    - Salak.Types.Value
    - Salak.Types.Selector
    - Salak.Types.Source
    - Salak.Load.Env
    - Salak.Load.Dynamic
    - Salak.Prop

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck < 2.14
      - salak-yaml
      - salak-toml
