_common: !include "../default.yaml"
name:                salak
synopsis:            Configuration (re)Loader and Parser.
<<: *legal
extra-source-files:
- README.md

dependencies:
  - base >= 4.10 && < 5
  - bytestring
  - containers
  - data-default
  - directory
  - dlist
  - exceptions
  - filepath
  - hashable
  - heaps
  - megaparsec
  - menshen
  - mtl
  - scientific
  - text
  - time
  - unliftio-core
  - unordered-containers

library:
  source-dirs: src
  exposed-modules:
    - Salak
    - Salak.Trie
    - Salak.Internal
  other-modules:
    - Salak.Internal.Key
    - Salak.Internal.Val
    - Salak.Internal.Source
    - Salak.Internal.Prop
    - Salak.Internal.Writable

benchmarks:
  salak-bench:
    main: SalakBench.hs
    source-dirs:
      - bench
    ghc-options: -main-is SalakBench.main -rtsopts -threaded -with-rtsopts=-K1K
    dependencies:
      - criterion
      - salak

tests:
  salak-spec:
    main: SalakSpec.hs
    source-dirs:
      - test
      - src
    ghc-options: -main-is SalakSpec.main -rtsopts -threaded -with-rtsopts=-K1K
    dependencies:
      - hspec == 2.*
      - QuickCheck < 2.14
      - random
    verbatim:
      build-tool-depends:
        hspec-discover:hspec-discover