_common: !include "../default.yaml"
name:                salak-test
version:             0.2.7
synopsis:            Configuration Loader for toml
<<: *legal
extra-source-files:
- README.md
- test/salak.yaml
- test/salak.toml

dependencies:
  - base >= 4.10 && < 5
  - salak == 0.2.7
  - salak-yaml == 0.2.7
  - salak-toml == 0.2.7

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec == 2.*
      - QuickCheck < 2.14
      - text
      - mtl